### ISSUE TITLE
USW012 - Vider le panier

### ISSUE THREAD

**Issue by oleflohic** [DTAFormation/pizzeria-app#28]
En tant que prospect, pouvoir vider le panier
Autrement dit : supprimer tout le contenu du panier.

**Critères :**
- Quand on clique sur un bouton nommé "Vider le panier" alerter le client qu'il s’apprête à vider son panier, et lui demander confirmation.
- S'il confirme, toutes les pizzas du panier sont supprimées de celui-ci.
- Suite à cette action, l'affichage du panier est mis à jour.
- S'il annule, aucune action n'est effectuée.

- Quand on valide une commande, le panier est vidé sans confirmation.

**Comment by roddet** [comment]
ajouter la confirmation.
bug affichage.
