### ISSUE TITLE
USA003 - Utilisateur - CRUD

### ISSUE THREAD

**Issue by roddet** [DTAFormation/pizzeria-app#3]
En tant qu'administrateur, je souhaite pouvoir gérer les utilisateurs (opérations CRUD).

Critères d'acceptation:
- On peux voir la liste de tous les utilisateurs disponibles (nom, prénom, email, mdp)
- On a un bouton pour chaque utilisateur permettant de modifier l'utilisateur
- On a un bouton permettant de supprimer un utilisateur (on peut supprimer uniquement les autres utilisateurs)
- On a un bouton pour créer un utilisateur : champ (nom, prénom, email, mdp) et un bouton permettant de créer l'utilisateur
- Tout les champs sont obligatoires (sauf nom et prénom), le mot de passe et l'email doivent être saisis deux fois a l'identique
- Le mot de passe doit être crypté en md5

**Comment by roddet** [comment]
Permettre d'éditer un utilisateur sans avoir à modifier son mot de passe

**Comment by amonmart** [comment]
Transfer vers USA021 - Problème de mot de passe non obligatoire pour éditer un utilisateur
