### ISSUE TITLE
USA017 - Identifiant fonctionnel pour les livreurs

### ISSUE THREAD

**Issue by amonmart** [DTAFormation/pizzeria-app#69]
Ajouter un identifiant fonctionnel au lignes de la table livreur.

**Critères d'acceptation** 
- Un identifiant fonctionnel doit être ajouté au modèle livreur. Cet identifiant sera composé des trois premières lettres du nom suivi des trois premières lettres du prénom (juxtaposé).
- Si jamais un identifiant doit être créé alors que un identifiant identique est déjà contenu dans la base, un nombre sera ajouté à la fin du nouvel identifiant.
 * Ce nombre correspond à l'identifiant technique de l'utilisateur.
- Mettre à jour les vues correspondantes pour afficher l'identifiant fonctionnel.
- L'identifiant fonctionnel ne doit pas changer après la création de l'utilisateur, même s'il devait mettre à jour son nom.

**Comment by oleflohic** [comment]
Potentiel problème : comment gérer les situations où le nom ou prénom fait moins de 3 caractères ?
