### ISSUE TITLE
USA009 - Envoyer emails aux clients

### ISSUE THREAD

**Issue by roddet** [DTAFormation/pizzeria-app#9]
En tant qu'administrateur, je souhaite pouvoir envoyer un email à tous les clients afin de les avertir d'une promotion.

critères d'acceptation:
- (On pré-sélectionne les destinataires ayant accepté de recevoir les promos)
- On a un page : un champ texte pour le message à envoyer et un bouton permettant d'envoyer les emails.
- Lors de l'envoi, on a une "pop-up" permettant de valider l'envoi des emails

**Comment by SamuelPerchaud** [comment]
utilisation d'un Serveur SMTP Gmail restreint, donc on ne peut envoyer des mails qu'a des clients possédant une adresse mail en Gmail.
pour utilisé un serveur smtp complet, il est nécessaire d'utilisé un serveur avec authentification.
